In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.ones(12)
b.resize(3, 4)
c = np.arange(0, 12).reshape(3, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
b.shape

(3, 4)

In [45]:
b.dtype

dtype('float64')

In [46]:
c = np.arange(0, 12).reshape(3, 4)
c[1][1]

np.int64(5)

In [47]:
c[1] # вторая строка

array([4, 5, 6, 7])

In [48]:
c[1:3, 2:] # с 2 по 3 строку, с 3 столбца до конца

array([[ 6,  7],
       [10, 11]])

In [49]:
c*2 # умножение каждого элемента на 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [50]:
b + c # поэлементное сложение массивов

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [51]:
c.mean() # среднее по всему массиву

np.float64(5.5)